### ISSUE TITLE
Proposal: ember-cli addon (or integration?)

### ISSUE THREAD

**Issue by kristianmandrup** [teddyzeenny/ember-mocha-adapter#29]
Would be great if there was an ember-cli addon _ember-cli-mocha_ which auto-configured mocha testing for an ember-cli app ;)

**Comment by jamesdixon** [comment]
@teddyzeenny does your adapter work with ember-cli-mocha or does it make it unnecessary?

**Comment by teddyzeenny** [comment]
@jamesdixon `ember-cli-mocha` uses this adapter as a [dependency](https://github.com/switchfly/ember-cli-mocha/blob/42cc756f61afecafeaba7fc4ea9fc37a4ca629ae/index.js#L71). So if you install `ember-cli-mocha` you'll also be using this adapter.
