### ISSUE TITLE
Possible to run single test file?

### ISSUE THREAD

**Issue by jme783** [teddyzeenny/ember-mocha-adapter#33]
Hi there,

I find that it slows me down to need to run ever single test every time that I want to re-run a particular test. Is there any sort of flag/setting to allow me to run test from a particular file?

Thanks!

Jeff

**Comment by teddyzeenny** [comment]
This is not related to this adapter. This depends on your test runner. Are you using ember-cli?

**Comment by jme783** [comment]
Yep, using ember-cli

**Comment by teddyzeenny** [comment]
ember-cli can help you filter. How do you run the tests?

**Comment by jme783** [comment]
I normally just run `ember test` or `ember test --server`

**Comment by teddyzeenny** [comment]
Assuming you want to run test containing the phrase  "creating comments" in its description:

`ember test --filter "creating comments"`

**Comment by jme783** [comment]
Ah cool! Does this need to be in a `describe()` specifically, or could it also be in an `it()` statement? Thanks so much for your help!!

**Comment by teddyzeenny** [comment]
I think `it` would work, you can try it out :)
