### ISSUE TITLE
Migrate into ember-mocha?

### ISSUE THREAD

**Issue by rwjblue** [teddyzeenny/ember-mocha-adapter#35]
I'd like to reduce the general number of "moving parts" in ember-mocha as I prepare to start working on implementation for https://github.com/emberjs/rfcs/pull/119.

@teddyzeenny - Would it be OK for me to inline the work you have done here, into ember-mocha (with proper credit of course)?

**Comment by teddyzeenny** [comment]
Sure :) Feel free to do whatever makes things easier for you. 
Thanks for working on https://github.com/emberjs/rfcs/pull/119

**Comment by Turbo87** [comment]
I think we can (and probably should) migrate away from `ember-mocha-adapter` in `ember-mocha` and `ember-cli-mocha`. Reason for this is that overriding `it()`, `beforeEach()`, `afterEach()`, ... has caused several problems in the past and seems largely incompatible with some changes in Mocha 3.x.

from what I understand we have two options to support our special async testing semantics:

- use something like `it('some test', wrapSpecialAsyncFoo(function() { ... }));`
- deprecate `it()` specs that use async functions but don't return a Promise

@dgeb @rwjblue @teddyzeenny opinions?

**Comment by Turbo87** [comment]
@teddyzeenny this issue can be closed, now that emberjs/ember-mocha#120 is merged! 🎉
